config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  draw :devise_routes
  draw :static_pages_routes

  # バッジの更新
  post 'update_badge_seen', to: 'whiskeys#update_badge_seen'
  post 'update_cocktail_badge_seen', to: 'cocktails#update_cocktail_badge_seen'
  # ユーザー関連のルーティング
  resources :users, only: %i[show edit update destroy]
  # カクテル関連のルーティング
  resources :cocktails do
    resources :cocktail_tastings, except: %i[index show]
    collection { get :bookmarks }
  end
  # ブックマークのルーティング
  resources :bookmarks, only: %i[create destroy]
  # ウイスキー関連のルーティング
  resources :whiskeys do
    member { get 'choose_next_step' }
    resources :tastings, except: %i[index show]
    collection do
      get :my_select
      get :random
    end
  end
  # 蒸留所のルーティング
  resources :distilleries, only: :index
  # 問い合わせフォームのルーティング
  resources :contacts, only: %i[new create] do
    collection do
      post 'confirm', 'back'
      get 'confirm', to: redirect('/contacts/new')
      get 'done'
    end
  end
end

app/models/cocktail.rb
# frozen_string_literal: true

# カクテルモデル
class Cocktail < ApplicationRecord
  belongs_to :base_cocktail
  has_many :cocktail_tastings, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_users, through: :bookmarks, source: :user

  scope :keyword, lambda { |word|
                    query = %w[cocktail_name cocktail_create cocktail_origin cocktail_recipe]
                            .map { |column| "#{column} LIKE :word" }
                            .join(' OR ')
                    where(query, word: "%#{word}%")
                  }
end

app/controllers/cocktails_controller.rb
# frozen_string_literal: true

# カクテルのコントローラ
class CocktailsController < ApplicationController
  skip_before_action :require_login

  def index
    @cocktail_search_form = SearchCocktailsForm.new(search_params)
    @cocktails = @cocktail_search_form.search.page(params[:page])
    @new_badges = fetch_new_badges if current_user.present?
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @cocktail_tastings = @cocktail.cocktail_tastings
    @next_cocktail = Cocktail.where('id > ?', @cocktail.id).order(:id).first
    @prev_cocktail = Cocktail.where('id < ?', @cocktail.id).order(:id).last
  end

  def update_cocktail_badge_seen
    # ユーザーの獲得したバッジの
    badges = current_user.user_cocktail_badges.where(cocktail_badge_id: params[:badge_ids])

    badges.each do |badge|
      badge.update(seen: true)
    end

    head :ok
  end

  private

  def search_params
    params.fetch(:search_cocktails_form, {}).permit(:keyword)
  end

  # index
  def fetch_new_badges
    current_user.user_cocktail_badges.where(seen: false)
                .includes(:cocktail_badge)
                .map(&:cocktail_badge)
                .as_json
  end
end

app/views/cocktails/_bookmark.html.erb
<%= link_to bookmarks_path(cocktail_id: cocktail.id), id: "js-bookmark-button-for-cocktail-#{cocktail.id}", class:"float-right", data: { turbo_method: :post }, title: "お気に入りに追加" do %>
   <i class="fa-solid fa-heart"></i>
<% end %>

app/views/cocktails/_bookmark_button.html.erb
<% if current_user.bookmark?(cocktail) %>
  <%= render 'unbookmark', { cocktail: cocktail } %>
<% else %>
  <%= render 'bookmark', { cocktail: cocktail } %>
<% end %>

app/views/cocktails/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(cocktail_id: cocktail.id)), id: "js-bookmark-button-for-cocktail-#{cocktail.id}", class:"float-right", data: { turbo_method: :delete } do %>
  <i class="fa-solid fa-heart fa-bounce" style="color: red;"></i>
<% end %>

app/views/cocktails/index.html.erb
<% breadcrumb :cocktails %>
<%= render 'shared/cocktail_search_form' %>
<div class="container">
  <%= render 'shared/badges' %>
  <div class="accordion accordion-flush pb-5" id="accordionFlushExample">
    <% @cocktails.each do |c| %>
    <div class="cocktail-data">
      <div class="card pt-3 pb-3 mt-5 ps-1">
        <div class="row">
          <div class="col-md-2">
            <% if c.cocktail_image.present? %>
            <%= image_tag "#{c.cocktail_image}", class: "cocktail-image" %>
            <% else %>
            <%= image_tag "bar.jpg", class: "cocktail-image" %>
            <% end %>
          </div>
          <div class="body col-md-2 ps-5">
            <div class="base-title">
              <%= c.base_cocktail.base_name %>
            </div>
            <%= link_to c.cocktail_name, cocktail_path(c), class: 'underline-animation' %>
          </div>
          <div class="cocktail-body col-md-4 d-flex align-items-center">
            <%= c.cocktail_origin %>
          </div>
          <% if user_signed_in? %>
          <div class="body col-md-3 ps-5">
            <%= link_to 'テイスティング登録', new_cocktail_cocktail_tasting_path(c) %>
          </div>
          <div class="body col-md-1">
            <div class="bookmark-container">
              <%= render 'cocktails/bookmark_button', cocktail: c %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <% if current_user && c.cocktail_tastings.where(user_id: current_user.id).present? %>
      <div class="accordion-item mb-3 rounded">
        <h2 class="accordion-header" id="heading-<%= c.id %>">
          <button class="accordion-button collapsed rounded" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-<%= c.id %>" aria-expanded="false" aria-controls="collapse-<%= c.id %>">
            <span class="text-center">テイスティング一覧</span>
          </button>
        </h2>
        <% c.cocktail_tastings.where(user_id: current_user.id).each do |f| %>
        <div id="collapse-<%= c.id %>" class="accordion-collapse collapse" aria-labelledby="heading-<%= c.id %>" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body row col-md-12">
            <span class="col-md-2">ウイスキー:<%= f.whiskey.name %></span>
            <span class="col-md-8">
              香り<%= image_tag 'https://cdnjs.cloudflare.com/ajax/libs/raty/3.1.1/images/star-on.png' %><span class="me-3"><%= f.aroma %></span>
              味<%= image_tag 'https://cdnjs.cloudflare.com/ajax/libs/raty/3.1.1/images/star-on.png' %><span class="me-3"><%= f.flavor %></span>
              見た目、色合い<%= image_tag 'https://cdnjs.cloudflare.com/ajax/libs/raty/3.1.1/images/star-on.png' %><span class="me-3"><%= f.appearance %></span>
              口当たり<%= image_tag 'https://cdnjs.cloudflare.com/ajax/libs/raty/3.1.1/images/star-on.png' %><span class="me-3"><%= f.mouthfeel %></span>
              後味<%= image_tag 'https://cdnjs.cloudflare.com/ajax/libs/raty/3.1.1/images/star-on.png' %><span class="me-3"><%= f.finish %></span>
              総合評価<%= image_tag 'https://cdnjs.cloudflare.com/ajax/libs/raty/3.1.1/images/star-on.png' %><span class="me-3"><%= (f.aroma + f.flavor + f.appearance + f.mouthfeel + f.finish) / 5 %></span>
            </span>
            <span class="col-md-2">
              <%= link_to t('helpers.btn.edit'), edit_cocktail_cocktail_tasting_path(c, f), class: 'btn btn-outline-primary' %>
              <%= link_to t('helpers.btn.destroy'), cocktail_cocktail_tasting_path(c, f), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' }, class: 'btn btn-outline-danger' %>
            </span>
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
    <% end %>
    <div class="mt-5"> <%= paginate @cocktails %> </div>
  </div>
  <style>
    .cocktail-image {
      @media (max-width:992px) {
        width: 90%;
        height: 80%;
      }
    }

    .cocktail-body {

      @media (max-width: 1500px; ) {
        padding-top: 100px;
      }

      @media (max-width: 992px) {
        font-size: 13px;
        text-align: center;
      }
    }
  </style>
  <script>
    document.addEventListener("turbo:load", function() {
        // ポップアップ表示の条件
        let newBadges = < %= @new_badges.to_json.html_safe % > ; // ERBで変数を埋め込む

        if (newBadges.length > 0) {

          let popup = document.getElementById("badge-popup");
          let badgeList = document.getElementById("badge-list");
          let Image = document.getElementById("badge-image");
          let closeBtn = document.querySelector(".popup .close");

          // ポップアップにバッジリストを追加
          newBadges.forEach(function(badge) {

              confetti({

                  particleCount: 500,
                  spread: 90,
                  origin: {
                    x: 0.5,
                    y: 0.5
                  }

                  ,
                  zIndex: 9999,
                }

              );

              let badgeItem = document.createElement("div");
              let badgeBox = document.createElement("div");
              let badgeImage = document.createElement("img");
              badgeImage.src = `<%=@new_badges.present? ? asset_path(@new_badges[0]["badge_image"]) : ''%>`;
              badgeImage.style.width = '400px';
              badgeImage.style.height = '150px';
              badgeItem.textContent = badge.name; // バッジ名を表示
              badgeBox.textContent = badge.description;
              badgeList.appendChild(badgeItem);
              badgeList.appendChild(badgeBox);
              Image.appendChild(badgeImage);
            }

          );

          // ポップアップ表示
          popup.style.display = "flex";

          // ポップアップ閉じる処理
          closeBtn.addEventListener("click", function() {
              popup.style.display = "none";



              // サーバーにポップアップ表示を通知する
              fetch("/update_cocktail_badge_seen", {

                  method: "POST",
                  headers: {
                    "Content-Type": "application/json",
                    "X-CSRF-Token": document.querySelector("meta[name='csrf-token']").getAttribute("content")
                  }

                  ,
                  body: JSON.stringify({
                      badge_ids: newBadges.map(badge => badge.id)
                    }

                  )
                  /*idsとすることで、同時に獲得したバッジを複数、seenをtrueにして表示させないようにしている*/
                }

              );
              location.reload();
            }

          );
        }
      }

    );
  </script>

app/views/cocktails/show.html.erb
<% breadcrumb :cocktail, @cocktail %>
<div class="container">
  <div class="row">
    <div class=" show-card col-md-6 bg-body-secondary shadow-lg rounded mb-2">
      <div class="show-frame mb-3">
        <div class="mb-4">
          <h1><%= @cocktail.cocktail_name %></h1>
        </div>
        <div class="mb-4">
          <h5>・カクテルの由来</h5><%= @cocktail.cocktail_origin %>
        </div>
        <div class="mb-4">
          <h5>・材料</h5><%= sanitize(@cocktail.cocktail_recipe.gsub(/,/, '<br>')) %>
        </div>
        <div class="mb-4">
          <h5>・簡単な作り方</h5><%= @cocktail.cocktail_create %>
        </div>
        <% if user_signed_in? %>
        <%= render 'cocktails/bookmark_button', cocktail: @cocktail %>
        <% end %>
      </div>
      <% if user_signed_in? %>
      <div class="cocktail-tasting mb-3">
        <%= link_to t('cocktails.show.link'), new_cocktail_cocktail_tasting_path(@cocktail) %>
      </div>
      <% end %>
    </div>
    <div class="col-md-6">
      <% if @cocktail.cocktail_url.present? %>
      <iframe width="500" height="400" src="https://www.youtube.com/embed/<%= @cocktail.cocktail_url %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <% else %>
      <p class='text-center mt-md-5'><%= t('cocktails.show.nul') %></p>
      <% end %>
    </div>
    <%= render 'shared/cocktail_pagenate' %>
  </div>
</div>
<style>
  iframe {
    @media (max-width: 992px) {
      width: 100%;
      height: 100%;
    }
  }

  .show-card {
    @media (max-width: 992px) {
      width: 80%;
    }
  }
</style>