config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  draw :devise_routes
  draw :static_pages_routes

  # バッジの更新
  post 'update_badge_seen', to: 'whiskeys#update_badge_seen'
  post 'update_cocktail_badge_seen', to: 'cocktails#update_cocktail_badge_seen'
  # ユーザー関連のルーティング
  resources :users, only: %i[show edit update destroy]
  # カクテル関連のルーティング
  resources :cocktails do
    resources :cocktail_tastings, except: %i[index show]
    collection { get :bookmarks }
  end
  # ブックマークのルーティング
  resources :bookmarks, only: %i[create destroy]
  # ウイスキー関連のルーティング
  resources :whiskeys do
    member { get 'choose_next_step' }
    resources :tastings, except: %i[index show]
    collection do
      get :my_select
      get :random
    end
  end
  # 蒸留所のルーティング
  resources :distilleries, only: :index
  # 問い合わせフォームのルーティング
  resources :contacts, only: %i[new create] do
    collection do
      post 'confirm', 'back'
      get 'confirm', to: redirect('/contacts/new')
      get 'done'
    end
  end
end

app/views/shared/_badges.html.erb
<div id="badge-popup" class="popup" style="display: none;">
  <div class="popup-content">
    <span class="close">&times;</span>
    <h2>新しいバッジがあります！</h2>
    <div id="badge-image"></div>
    <div id="badge-list"></div>
  </div>
</div>

app/views/shared/_cocktail_pagenate.html.erb
<nav aria-label="Cocktail navigation">
  <ul class="pagination d-flex justify-content-between">
    <li class="page-item">
      <% if @prev_cocktail %>
        <%= link_to cocktail_path(@prev_cocktail), class: "page-link", aria: { label: "Previous" } do %>
          <span aria-hidden="true">&laquo; 前のカクテル</span>
        <% end %>
      <% else %>
        <span class="page-link disabled" aria-hidden="true">&laquo; 前のカクテル</span>
      <% end %>
    </li>
    <li class="page-item">
      <% if @next_cocktail %>
        <%= link_to cocktail_path(@next_cocktail), class: "page-link", aria: { label: "Next" } do %>
          <span aria-hidden="true">次のカクテル &raquo;</span>
        <% end %>
      <% else %>
        <span class="page-link disabled" aria-hidden="true">次のカクテル &raquo;</span>
      <% end %>
    </li>
  </ul>
</nav>

app/views/shared/_cocktail_search_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <%= form_with model: @cocktail_search_form, url: cocktails_path, method: :get, class: 'search-form col-12 col-md-10 col-lg-8' do |f| %>
      <div class="row">
        <div class="col-12">
          <%= f.text_field :keyword, class: 'form-control', placeholder: 'キーワードを入力' %>
        </div>
        <div class="col-12 mb-3">
          <%= f.submit t('helpers.submit.search'), class: 'btn btn-success w-100' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> text-bg-dark p-3">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='position: sticky;'>
  <div class='container-fluid'>
    <div class='row'>
      <div class='col-md-6 text-start'>
        <ul class='list-unstyled'>
          <li>
            <%= link_to "/利用規約.pdf",target: '_blank', rel: 'noopener', class: "link-light link-offset-2 link-underline-opacity-25 link-underline-opacity-75-hover" do %><%= t('.rule') %><% end %>
          </li>
          <li>
            <%= link_to "https://kiyac.app/privacypolicy/b149NohP0sP9Zo9fMAsh", class: "link-light link-offset-2 link-underline-opacity-25 link-underline-opacity-75-hover" do %><%= t('.private') %><% end %>
          </li>
        </ul>
      </div>
      <div class='col-md-6 text-end'>
        <p class="mb-0">Copyright © 2024. TXOXU</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="fixed-top">
  <nav class='navbar navbar-expand-lg navbar-light'>
    <%= link_to root_path, class: 'navbar-brand' do %>
    <h4 class="main-title"><%= t('.title') %></h4>
    <% end %>
    <button id="btn">ダークモード</button>

    <button class='navbar-toggler' type='button' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <% if user_signed_in? %>
      <ul class='navbar-nav ms-auto align-items-center me-4'>
        <li class='nav-item dropdown'>
          <%= link_to t('.whiskey'), '#', class: 'nav-link dropdown-toggle', data: { bs_toggle: 'dropdown'}, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-whiskey-new' %>
          <div class='dropdown-menu dropdown-menu-end'>
            <%= link_to t('.whiskey_new'), new_whiskey_path, class: 'dropdown-item' %>
            <%= link_to t('.whiskey_index'), whiskeys_path, class: 'dropdown-item' %>
            <%= link_to t('.whiskey_select'), my_select_whiskeys_path, class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-item dropdown'>
          <%= link_to 'カクテル', '#', class: 'nav-link dropdown-toggle', data: { bs_toggle: 'dropdown'}, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-board-menu' %>
          <div class='dropdown-menu dropdown-menu-end'>
            <%= link_to 'カクテル一覧', cocktails_path, class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-item dropdown'>
          <%= link_to '蒸留所', '#', class: 'nav-link dropdown-toggle', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-board-menu' %>
          <div class='dropdown-menu dropdown-menu-end'>
            <%= link_to '蒸留所一覧', distilleries_path, class: 'dropdown-item', data: {"turbolinks" => false} %>
          </div>
        </li>
        <li class='nav-item'>
          <%= link_to mypage_path, class: 'nav-link', id: "header-mypage" do %><%= t('.mypage') %><% end %>
        </li>
        <li class='nav-item dropdown'>
          <%= link_to '#', class: 'nav-link dropdown-toggle', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-profile' do %>
          <%= image_tag 'top.jpg', class: 'rounded-circle', style: "border: 1px solid #000;", width: '40', height: '40' %>
          <% end %>
          <div class='dropdown-menu dropdown-menu-end'>
            <div class='dropdown-item'><%= link_to current_user.name, user_path(current_user) %></div>
            <div class='dropdown-divider'></div>
            <%= link_to "このアプリについて", explanation_path, class: 'dropdown-item'%>
            <%= link_to "お問い合わせ", new_contact_path, class: 'dropdown-item' %>
            <%= link_to t('.logout'), destroy_user_session_path, class: 'dropdown-item', data: { turbo_method: :delete } %>
          </div>
        </li>
      </ul>
      <% else %>
      <ul class='navbar-nav ms-auto align-items-center me-4'>
        <li class='nav-item dropdown'>
          <%= link_to 'カクテル', '#', class: 'nav-link dropdown-toggle', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-cocktail-index' %>
          <div class='dropdown-menu dropdown-menu-end'>
            <%= link_to 'カクテル一覧', cocktails_path, class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-item dropdown'>
          <%= link_to '蒸留所', '#', class: 'nav-link dropdown-toggle', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-distillery-index' %>
          <div class='dropdown-menu dropdown-menu-end'>
            <%= link_to '蒸留所一覧', distilleries_path, class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-item'>
          <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
        </li>
        <li class='nav-item'>
          <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class='nav-item'>
          <%= link_to "このアプリについて", explanation_path, class: 'nav-link'%>
        </li>
      </ul>
      <% end %>
    </div>
  </nav>
</header>
<script>

</script>

app/views/shared/_search_form.html.erb
<div class="container">
  <div class="row">
    <%= form_with model: @search_form, url: whiskeys_path, method: :get, local: true, class: 'search-form d-flex flex-wrap' do |f| %>
      <div class="col-md-2 me-1">
        <%= f.select :category_names, options_for_select(@category_names.map(&:category_name)), {include_blank: '生産国別'}, class: 'form-select form-select-md' %>
      </div>
      <div class="col-md-2 me-1">
        <%= f.select :category_types, options_for_select(@category_types.map(&:category_type)), {include_blank: '原産国別'}, class: 'form-select' %>
      </div>
      <div class="col-md-3 me-1">
        <%= f.text_field :name, class: 'form-control', placeholder: 'ウイスキーの名前' %>
      </div>
      <div class="col-md-3">
        <%= f.text_field :text, class: 'form-control', placeholder: 'キーワード' %>
      </div>
      <div class="col-md-12 mt-1 mb-3">
        <%= f.submit t('helpers.submit.search'), class: 'btn btn-outline-success w-100' %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_whiskey_pagenate.html.erb
<nav aria-label="Whiskey navigation">
  <ul class="pagination d-flex justify-content-between">
    <li class="page-item">
      <% if @prev_whiskey %>
        <%= link_to whiskey_path(@prev_whiskey), class: "page-link", aria: { label: "Previous" } do %>
          <span aria-hidden="true">&laquo; 前のウイスキー</span>
        <% end %>
      <% else %>
        <span class="page-link disabled" aria-hidden="true">&laquo; 前のウイスキー</span>
      <% end %>
    </li>
    <li class="page-item">
      <% if @next_whiskey %>
        <%= link_to whiskey_path(@next_whiskey), class: "page-link", aria: { label: "Next" } do %>
          <span aria-hidden="true">次のウイスキー &raquo;</span>
        <% end %>
      <% else %>
        <span class="page-link disabled" aria-hidden="true">次のウイスキー &raquo;</span>
      <% end %>
    </li>
  </ul>
</nav>