config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  draw :devise_routes
  draw :static_pages_routes

  # バッジの更新
  post 'update_badge_seen', to: 'whiskeys#update_badge_seen'
  post 'update_cocktail_badge_seen', to: 'cocktails#update_cocktail_badge_seen'
  # ユーザー関連のルーティング
  resources :users, only: %i[show edit update destroy]
  # カクテル関連のルーティング
  resources :cocktails do
    resources :cocktail_tastings, except: %i[index show]
    collection { get :bookmarks }
  end
  # ブックマークのルーティング
  resources :bookmarks, only: %i[create destroy]
  # ウイスキー関連のルーティング
  resources :whiskeys do
    member { get 'choose_next_step' }
    resources :tastings, except: %i[index show]
    collection do
      get :my_select
      get :random
    end
  end
  # 蒸留所のルーティング
  resources :distilleries, only: :index
  # 問い合わせフォームのルーティング
  resources :contacts, only: %i[new create] do
    collection do
      post 'confirm', 'back'
      get 'confirm', to: redirect('/contacts/new')
      get 'done'
    end
  end
end

app/models/contact.rb
# frozen_string_literal: true

# お問い合わせに関するモデル
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :subject, presence: true
  validates :message, presence: true
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

# お問い合わせ機能のコントローラ
class ContactsController < ApplicationController
  skip_before_action :require_login
  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      flash[:alert] = @contact.errors.full_messages
      render :new
    else
      render :confirm
    end
  end

  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_contacts_path
    else
      flash[:alert] = @contact.errors.full_messages
      @contact = Contact.new
      render :new
    end
  end

  def done; end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :subject, :message)
  end
end

app/views/contacts/confirm.html.erb
<div class="container">
  <div class="row">
    <div class="card col-md-7 offset-md-2">
      <div class="card-body">
        <h5 class="card-title pb-3">
          <span class="title">お名前</span>
          <%= @contact.name %>
        </h5>
        <h6 class="card-subtitle mb-2 text-body-secondary pb-3">
          <span class="title">メールアドレス</span>
          <%= @contact.email %>
        </h6>
        <h6 class="card-subject pb-3">
          <span class="title">件名</span>
          <%= @contact.subject %>
        </h6>
        <p class="card-message pb-3">
          <span class="title">メッセージ</span>
          <%= @contact.message %>
        </p>
          <div class="card-link">
            <%= form_with model: @contact, url: contacts_path, local: true, data: { turbo: false } do |f| %>
            <%= f.hidden_field :name %>
            <%= f.hidden_field :email %>
            <%= f.hidden_field :subject %>
            <%= f.hidden_field :message %>
            <div><%= f.submit '送信', class: "btn btn-success w-100" %></div>
          <% end %>
            <%= form_with model: @contact, url: back_contacts_path, local: true, data: { turbo: false } do |f| %>
            <%= f.hidden_field :name %>
            <%= f.hidden_field :email %>
            <%= f.hidden_field :subject %>
            <%= f.hidden_field :message %>
            <div><%= f.submit '入力画面に戻る', class: "btn btn-info w-100" %></div>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/done.html.erb
<div class="container p-5">
  <div class="row">
    <div class="card mt-5 pt-5 pb-5 bg-body-secondary">
      <h5 class="text-center">お問い合わせありがとうございました。<br>今後ともよろしくお願いいたします。</h5>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container-fluid light-blue-container p-5">
  <div class="row">
    <div class="card col-md-7 offset-md-2 p-md-3">
      <%= form_with model: @contact, url: confirm_contacts_path, method: :post, local: true, data: { turbo: false } do |f| %>
        <div class="form-group mb-3">
          <%= f.label :name, 'お名前' %><span class="text-danger">*</span>
          <%= f.text_field :name, autofocus: true, class: 'form-control' %>
        </div>

        <div class="form-group mb-3">
          <%= f.label :email, 'メールアドレス' %><span class="text-danger">*</span>
          <%= f.email_field :email, class: 'form-control' %>
        </div>

        <div class="form-group mb-3">
          <%= f.label :subject, '件名' %><span class="text-danger">*</span>
          <%= f.text_area :subject, class: 'form-control' %>
        </div>

        <div class="form-group mb-3">
          <%= f.label :message, 'メッセージ' %><span class="text-danger">*</span>
          <%= f.text_area :message, size: '10x10', class: 'form-control' %>
        </div>

        <div class="text-center">
          <%= f.submit '入力内容確認', class: "btn btn-outline-info bg-white w-100" %>
        </div>
      <% end %>

    </div>
  </div>
</div>