config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  draw :devise_routes
  draw :static_pages_routes

  # バッジの更新
  post 'update_badge_seen', to: 'whiskeys#update_badge_seen'
  post 'update_cocktail_badge_seen', to: 'cocktails#update_cocktail_badge_seen'
  # ユーザー関連のルーティング
  resources :users, only: %i[show edit update destroy]
  # カクテル関連のルーティング
  resources :cocktails do
    resources :cocktail_tastings, except: %i[index show]
    collection { get :bookmarks }
  end
  # ブックマークのルーティング
  resources :bookmarks, only: %i[create destroy]
  # ウイスキー関連のルーティング
  resources :whiskeys do
    member { get 'choose_next_step' }
    resources :tastings, except: %i[index show]
    collection do
      get :my_select
      get :random
    end
  end
  # 蒸留所のルーティング
  resources :distilleries, only: :index
  # 問い合わせフォームのルーティング
  resources :contacts, only: %i[new create] do
    collection do
      post 'confirm', 'back'
      get 'confirm', to: redirect('/contacts/new')
      get 'done'
    end
  end
end

app/models/whiskey.rb
# frozen_string_literal: true

# ウイスキーに関するモデル
class Whiskey < ApplicationRecord
  has_many :whiskey_categories, dependent: :destroy
  has_many :categories, through: :whiskey_categories
  has_many :tastings, dependent: :destroy
  has_many :cocktail_tastings, dependent: :destroy
  belongs_to :user
  belongs_to :remmaining_quantity, optional: true

  mount_uploader :image, ImageUploader, ignore_integrity_errors: true

  validates :name, presence: true
  validate :validate_image

  scope :by_category_ids, ->(ids) { joins(:categories).where(categories: { id: ids }) }
  scope :name_contain, ->(word) { where('name LIKE ?', "%#{word}%") }
  scope :text_contain, ->(word) { where('text LIKE ?', "%#{word}%") }

  def assign_remmaining_quantity(quantity)
    self.remmaining_quantity = quantity.presence || nil
  end

  def assign_image(image)
    self.image = image.presence || File.open(Rails.root.join('app/assets/images/default.jpg'))
  end

  private

  def validate_image
    return unless image.present? && !image.file.extension.in?(%w[jpg jpeg png gif])

    errors.add(:image, 'は jpg, jpeg, png, gif のいずれかの形式でアップロードしてください')
  end
end

app/controllers/whiskeys_controller.rb
# frozen_string_literal: true

# ウイスキーのコントローラ
class WhiskeysController < ApplicationController
  before_action :set_whiskey, only: %i[edit update destroy choose_next_step]
  before_action :prepare_form_data, only: %i[new edit create index]

  def new
    @whiskey = Whiskey.new
  end

  def create
    @whiskey = current_user.whiskeys.build(whiskey_params)
    categories = find_existing_categories
    remmaining_quantity = RemmainingQuantity.find_by(id: params[:whiskey][:remmaining_quantity_id])

    if categories.any?
      save_whiskey_with_categories(categories, remmaining_quantity)
    else
      flash.now[:danger] = t('whiskeys.create.danger')
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @search_form = SearchWhiskeysForm.new(search_params)
    @whiskeys = @search_form.search.where(user_id: current_user.id).page(params[:page])
    @tastings = Tasting.where(whiskey_id: @whiskeys.pluck(:id))
    @new_badges = fetch_new_badges
  end

  def edit; end

  def update
    categories = find_existing_categories
    remmaining_quantity = RemmainingQuantity.find_by(id: params[:whiskey][:remmaining_quantity_id])

    if @whiskey.update(whiskey_params)
      process_successful_update(categories, remmaining_quantity)
    else
      flash.now[:danger] = t('whiskeys.update.danger')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @whiskey.destroy!
    redirect_to whiskeys_path, danger: t('whiskeys.destroy.danger'), status: :see_other
  end

  def choose_next_step; end

  def my_select; end

  def random
    @whiskeys = current_user.whiskeys.all
    @whiskey = @whiskeys.sample
    render json: { name: @whiskey.name }
  end

  def update_badge_seen
    badges = current_user.user_whiskey_badges.where(whiskey_badge_id: params[:badge_ids])

    badges.each do |badge|
      badge.update(seen: true)
    end

    head :ok
  end

  private

  def whiskey_params
    params.require(:whiskey).permit(:name, :text, :image, :remmaining_quantity_id, category_names: [],
                                                                                   category_types: [])
  end

  def search_params
    params.fetch(:search_whiskeys_form, {}).permit(%i[category_names category_types name text])
  end

  def set_whiskey
    @whiskey = current_user.whiskeys.find(params[:id])
  end

  def prepare_form_data
    @category_names = Category.select(:category_name).distinct
    @category_types = Category.select(:category_type).distinct
    @quantities = RemmainingQuantity.all
  end

  # create update
  def assign_save(categories, remmaining_quantity)
    @whiskey.assign_image(params[:whiskey][:image])
    @whiskey.assign_remmaining_quantity(remmaining_quantity)
    @whiskey.categories << categories
  end

  def find_existing_categories
    Category.where(category_name: params[:whiskey][:category_names])
            .where(category_type: params[:whiskey][:category_types])
  end

  # update
  def process_successful_update(categories, remmaining_quantity)
    assign_update(categories, remmaining_quantity)
    redirect_to whiskeys_path, success: t('whiskeys.update.success')
  end

  def assign_update(categories, remmaining_quantity)
    @whiskey.assign_image(params[:whiskey][:image])
    @whiskey.assign_remmaining_quantity(remmaining_quantity)
    @whiskey.categories = categories
  end

  # index
  def fetch_new_badges
    current_user.user_whiskey_badges.where(seen: false)
                .includes(:whiskey_badge)
                .map(&:whiskey_badge)
                .as_json
  end

  # create
  def save_whiskey_with_categories(categories, remmaining_quantity)
    if @whiskey.save
      assign_save(categories, remmaining_quantity)
      WhiskeyBadgesJob.perform_later(current_user.id, @whiskey.id)
      redirect_to choose_next_step_whiskey_path(@whiskey), success: t('whiskeys.create.success')
    else
      flash.now[:danger] = t('whiskeys.create.danger')
      render :new, status: :unprocessable_entity
    end
  end
end

app/views/whiskeys/_search_form.html.erb
<%= form_with model: @search_form, url: whiskeys_path, method: :get, local: true do |f| %>
  <div class="row align-items-center">
    <div class="col-md-2">
      <div class="form-group">
        <%= f.label :category_names, '国別' %>
        <%= f.select :category_names, options_for_select(@category_names.map(&:category_name)), include_blank: true, class: 'form-control' %>
      </div>
    </div>
    
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :category_types, '原料別' %>
        <%= f.select :category_types, options_for_select(@category_types.map(&:category_type)), include_blank: true, class: 'form-control' %>
      </div>
    </div>
    
    <div class="col-md-3">
      <div class="form-group d-flex align-items-center">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    
    <div class="col-md-3">
      <div class="form-group  d-flex align-items-center">
        <%= f.label :text, '説明' %>
        <%= f.text_field :text, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-1">
      <div class="form-group ">
        <%= f.submit '検索', class: 'btn btn-primary' %>
      </div>
    </div>
  </div>

  
<% end %>

app/views/whiskeys/choose_next_step.html.erb
<div class="bg-body-secondary shadow-lg rounded pt-5">
  <div class="container">
    <div class="row">
      <h1><%= t('.title') %></h1>
      <p><%= t('.select') %></p>

      <div class="col-md-6 mb-5">
        <%= link_to t('.next_tasting'), new_whiskey_tasting_path(@whiskey), class: 'btn btn-outline-primary' %>
        <%= link_to t('.whiskey_new'), new_whiskey_path, class: 'btn btn-outline-info' %>
        <%= link_to t('.whiskeys'), whiskeys_path, class: 'btn btn-outline-secondary' %>
      </div>
    </div>
  </div>
</div>

app/views/whiskeys/edit.html.erb
<% breadcrumb :edit_whiskey, @whiskey %>

<div class="container edit bg-body-secondary shadow-lg rounded pt-3 pb-3">
  <div class="row">
    <div class="col-md-6">
      <div class="edit-frame">
        <div class="whiskey-edit">
          <h1><%= t('.title') %></h1>
        </div>
        <%= form_with model: @whiskey, id: 'edit_whiskey', local: true do |f| %>
        <div class="mb-3">
          <%= f.label :name %><span class="text-danger">*</span>
          <%= f.text_field :name, class: "form-control", required: true %>
        </div>
        <div class="mb-3">
          <%= f.label :text %>
          <%= f.text_field :text, class: "form-control" %>
        </div>
        <div class="mb-3" id="form-quantity" style="display:none;">
          <%= f.label :remmaining_quantity_id %>
          <%= f.collection_radio_buttons :remmaining_quantity_id, @quantities, :id, :quantity, class: "form-check-input", required: true do |rb| %>
          <%= rb.radio_button %>
          <%= rb.label(class: "form-check-label") %>
          <% end %>

          <div class="form-check form-check-inline">
            <%= f.radio_button :remmaining_quantity_id, '', class: "form-check-input" %>
            <%= f.label :remmaining_quantity_id, "指定しない", class: "form-check-label" %>
          </div>
        </div>

        <div class="mb-3" id="form-image">
          <%= f.label :image %>
          <%= f.file_field :image, class: "form-control" %>
        </div>

        <div class="row">
          <div class="btn-group-vertical col-3" role="group" aria-label="Vertical radio toggle button group">
            <input type="radio" class="btn-check" name="vbtn-radio" id="vbtn-radio1" autocomplete="off" checked>
            <label class="btn btn-outline-danger" for="vbtn-radio1">画像ファイル</label>
            <input type="radio" class="btn-check" name="vbtn-radio" id="vbtn-radio2" autocomplete="off">
            <label class="btn btn-outline-danger" for="vbtn-radio2">量機能</label>
          </div>
          <div class="col-9">
            <p>*実際の写真を使って量を管理することも、提供されている画像を参考に設定することも可能です。</p>
            <p>*スマートフォン等で写真を撮り直接保存することはできません</p>
          </div>
        </div>

        <div class="mb-3">
          <%= f.label :category_names %><span class="text-danger">*</span>
          <%= f.select :category_names, @category_names.map { |c| c.category_name }, { prompt: "選択してください" }, class: "form-control", required: true %>
        </div>
        <div class="mb-3">
          <%= f.label :category_types %><span class="text-danger">*</span>
          <%= f.select :category_types, @category_types.map { |c| c.category_type }, { prompt: "選択してください" }, class: "form-control", required: true %>
        </div>
        <div class="actions">
          <%= f.submit t('helpers.submit.create'), class: "btn btn-outline-primary" %>
        </div>
        <% end %>
      </div>
    </div>

    <div class="col-md-6" id='previews-form'>
      <div class="image-container text-center">
        <div id="previews" class="border p-3">
          <%= t('helpers.preview') %>
        </div>
      </div>
    </div>

    <div class="col-md-6" id='quantity-previews-form'>
      <div class="quantity-container text-center">
        <div id="quantity-previews" class="border p-3">
          <%= t('helpers.preview') %>
        </div>
      </div>
    </div>
  </div>
</div>
<style>
  .edit {
    @media (max-width: 992px) {
      width: 90%;
    }
  }

  .btn-outline-danger {
    font-size: 15px;

    @media (max-width: 992px) {
      font-size: 8px;
      padding-left: 5px;
      padding-right: 5px;
    }
  }

  .actions {
    @media (max-width: 992px) {
      display: flex;
      justify-content: center;
    }
  }
</style>

app/views/whiskeys/index.html.erb
<% breadcrumb :whiskeys %>
<%= render 'shared/search_form' %>
<div class="container">
  <div class="row">
    <%= render 'shared/badges' %>
    <% if current_user.whiskeys.present? %>
    <% @whiskeys.each do |whiskey| %>
    <div class="whiskey-data col-lg-12 mb-5">
      <div class="card mb-2 shadow-lg">
        <div class="row g-0">
          <!-- 画像と数量の部分をレスポンシブに調整 -->
          <div class="image-space col-md-4 col-sm-6">
            <% if whiskey.image.present? %>
            <%= image_tag whiskey.image.url, class: "img-fluid rounded-start", size: '250x300' %>
            <% else %>
            <%= image_tag "default.jpg", class: "img-fluid rounded-start", size: '250x300' %>
            <% end %>
          </div>
          <div class="col-md-4 col-sm-6">
            <% if whiskey.remmaining_quantity.present? && whiskey.remmaining_quantity.quantity_image.present? %>
            <%= image_tag whiskey.remmaining_quantity.quantity_image, size: '250x300' %>
            <% else %>
            <p class="pt-5">量は設定されていません</p>
            <% end %>
          </div>
          <div class="col-md-4">
            <div class="card-body">
              <h3 class="card-title"><%= whiskey.name %></h3>
              <% if whiskey.remmaining_quantity.present? && whiskey.remmaining_quantity.quantity.present? %>
              <p class="card-text"><%= whiskey.remmaining_quantity.quantity %></p>
              <% end %>
              <% whiskey.categories.each do |c| %>
              <p class="card-text"><small class="text-body-secondary"><%= c.category_name %></small></p>
              <p class="card-text"><small class="text-body-secondary"><%= c.category_type %></small></p>
              <% end %>
              <p class="card-text"><small class="text-body-success"><%= whiskey.text %></small>
              <p class="card-text">
                <%= link_to t('.add_tasting'), new_whiskey_tasting_path(whiskey), class: 'btn btn-outline-primary btn-sm' %>
                <%= link_to t('helpers.btn.edit'), edit_whiskey_path(whiskey), class: 'btn btn-outline-secondary btn-sm' %>
                <%= link_to t('helpers.btn.destroy'), whiskey_path(whiskey), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' }, class: 'btn btn-outline-danger btn-sm' %>
              </p>
            </div>
          </div>
        </div>
      </div>

      <% if @tastings.where(whiskey_id: whiskey.id).present? %>
      <div class="accordion" id="accordion-<%= whiskey.id %>">
        <div class="accordion-item">
          <h2 class="accordion-header" id="heading-<%= whiskey.id %>">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-<%= whiskey.id %>" aria-expanded="false" aria-controls="collapse-<%= whiskey.id %>">
              テイスティング一覧
            </button>
          </h2>
          <div id="collapse-<%= whiskey.id %>" class="accordion-collapse collapse" aria-labelledby="heading-<%= whiskey.id %>" data-bs-parent="#accordion-<%= whiskey.id %>">
            <div class="accordion-body">
              <% @tastings.where(whiskey_id: whiskey.id).each do |f| %>
              <div class="card text-center mb-3 shadow-lg">
                <div class="card-header">
                  <%= f.tasting_type %>
                </div>
                <div class="card-body">
                  <h5 class="card-title">
                    総合評価
                    <%= image_tag 'https://cdnjs.cloudflare.com/ajax/libs/raty/3.1.1/images/star-on.png' %>
                    <%= (f.aroma + f.flavor + f.balance + f.body + f.finish) / 5 %>
                  </h5>
                  <p class="card-text">
                    香り<%= image_tag 'https://cdnjs.cloudflare.com/ajax/libs/raty/3.1.1/images/star-on.png' %><span class="me-3"><%= f.aroma %></span>
                    味<%= image_tag 'https://cdnjs.cloudflare.com/ajax/libs/raty/3.1.1/images/star-on.png' %><span class="me-3"><%= f.flavor %></span>
                    バランス<%= image_tag 'https://cdnjs.cloudflare.com/ajax/libs/raty/3.1.1/images/star-on.png' %><span class="me-3"><%= f.balance %></span>
                    濃さ<%= image_tag 'https://cdnjs.cloudflare.com/ajax/libs/raty/3.1.1/images/star-on.png' %><span class="me-3"><%= f.body %></span>
                    余韻<%= image_tag 'https://cdnjs.cloudflare.com/ajax/libs/raty/3.1.1/images/star-on.png' %><span class="me-3"><%= f.finish %></span>
                  </p>
                  <div class="actions">
                    <%= link_to t('helpers.btn.edit'), edit_whiskey_tasting_path(whiskey, f), class: 'btn btn-outline-primary' %>
                    <%= link_to t('helpers.btn.destroy'), whiskey_tasting_path(whiskey, f), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' }, class: 'btn btn-outline-danger' %>
                  </div>
                </div>
                <div class="card-footer text-body-secondary">
                  <%= f.tasting_text %>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
    <%= paginate @whiskeys, class: 'pagination justify-content-center' %>
    <% else %>
    <h4 class="text-center mt-5"><%= t('.not_whiskeys') %></h4>
    <% end %>
  </div>
</div>
<style>
  .img-fluid {
    @media (max-width: 992px) {
      width: 100%;
    }
  }
</style>



<script>
  document.addEventListener("turbo:load", function() {
      // ポップアップ表示の条件

      let newBadges = < %= @new_badges.to_json.html_safe % > ; // ERBで変数を埋め込む

      if (newBadges.length > 0) {

        let popup = document.getElementById("badge-popup");
        let badgeList = document.getElementById("badge-list");
        let Image = document.getElementById("badge-image");
        let closeBtn = document.querySelector(".popup .close");

        // ポップアップにバッジリストを追加
        newBadges.forEach(function(badge) {

            confetti({

                particleCount: 500,
                spread: 90,
                origin: {
                  x: 0.5,
                  y: 0.5
                }

                ,
                zIndex: 9999,
              }

            );

            let badgeItem = document.createElement("div");
            let badgeBox = document.createElement("div");
            let badgeImage = document.createElement("img");
            badgeImage.src = `<%=@new_badges.present? ? asset_path(@new_badges[0]["badge_image"]) : ''%>`;
            badgeImage.style.width = '400px';
            badgeImage.style.height = '150px';
            badgeItem.textContent = badge.name; // バッジ名を表示
            badgeBox.textContent = badge.description;
            badgeList.appendChild(badgeItem);
            badgeList.appendChild(badgeBox);
            Image.appendChild(badgeImage);
          }

        );

        // ポップアップ表示
        popup.style.display = "flex";

        // ポップアップ閉じる処理
        closeBtn.addEventListener("click", function() {
            popup.style.display = "none";



            // サーバーにポップアップ表示を通知する
            fetch("/update_badge_seen", {

                method: "POST",
                headers: {
                  "Content-Type": "application/json",
                  "X-CSRF-Token": document.querySelector("meta[name='csrf-token']").getAttribute("content")
                }

                ,
                body: JSON.stringify({
                    badge_ids: newBadges.map(badge => badge.id)
                  }

                )
              }

            );
            location.reload();
          }

        );
      }
    }

  );
</script>

app/views/whiskeys/my_select.html.erb
<div class="container ">
  <div class="row">
    <div class="select-whiskey">
      <div class="select-card card ">
        <div class="card-title pt-5">
          <h2 class="select-size">今日の一杯！！</h2>
        </div>
        <div id="my-selecter" data-name="">
        </div>
        <div class=" card-button pt-3 pb-3">
          <%= link_to "今日の一杯を選ぶ", random_whiskeys_path, class: "btn btn-primary", id: "my-select" %>
        </div>
        <div class="card-text mb-5 pt-2">
          <h5 class="select-size">ボタンを押して、<br>今日の一杯を決めてください！</h5>
        </div>
      </div>
    </div>
  </div>
  <style>
    .select-card {
      width: 60%;
      align-items: center;
    }

    .select-whiskey {
      display: flex;
      justify-content: center;
      margin-bottom: 300px;
    }

    .select-size {
      @media (max-width: 992px) {
        font-size: 13px;
      }
    }
  </style>
  <script>
    // ページ全体を初回ページ読み込み時にイベントを発生させる
    document.addEventListener('turbo:load', function() {

      //idがselectの要素を取り出し定数selectへ代入、selecterも同様
      const mySelect = document.getElementById('my-select');
      const mySelecter = document.getElementById('my-selecter');

      //selectがクリックされたときにイベントを発生
      mySelect.addEventListener('click', function(event) {
        event.preventDefault(); // デフォルトのリンク動作を無効化

        // 非同期リクエストを送信
        fetch('/whiskeys/random.json')
          .then(response => response.json()) // JSON形式でレスポンスを解析
          .then(data => {
            mySelecter.innerHTML = data.name + "で一杯";
          })
          .catch(error => {
            mySelecter.innerHTML = `<span class="alert">ウイスキーが登録されていません。</span><a href="/whiskeys/new" style="color: blue; text-decoration: underline;">
            ウイスキーを登録する
          </a>`
          });
      });
    });
  </script>

app/views/whiskeys/new.html.erb
<% breadcrumb :new_whiskey %>
<div class="container new bg-body-secondary shadow-lg rounded pt-3 pb-3">
  <div class="row">
    <div class="col-md-6">
      <div class="whiskey-frame">
        <div class="whiskey-new">
          <h1><%= t('.title') %></h1>
        </div>
        <%= form_with model: @whiskey, id: 'new_whiskey', local: true do |f| %>
        <div class="mb-3">
          <%= f.label :name %><span class="text-danger">*</span>
          <%= f.text_field :name, class: "form-control", required: true %>
        </div>

        <div class="mb-3">
          <%= f.label :text %>
          <%= f.text_area :text, class: "form-control" %>
        </div>

        <div class="mb-3" id="form-quantity" style="display:none;">
          <%= f.label :remmaining_quantity_id, "ウイスキーの量" %>
          <%= f.collection_radio_buttons :remmaining_quantity_id, @quantities, :id, :quantity, required: true do |rb| %>
          <div class="form-check form-check-inline">
            <%= rb.radio_button(class: "form-check-input") %>
            <%= rb.label(class: "form-check-label") %>
          </div>
          <% end %>

          <div class="form-check form-check-inline">
            <%= f.radio_button :remmaining_quantity_id, '', class: "form-check-input" %>
            <%= f.label :remmaining_quantity_id, "指定しない", class: "form-check-label" %>
          </div>
        </div>

        <div class="mb-3" id="form-image">
          <%= f.label :image %>
          <%= f.file_field :image, class: "form-control" %>
        </div>
        <div class="row">
          <div class="btn-group-vertical col-3" role="group" aria-label="Vertical radio toggle button group">
            <input type="radio" class="btn-check" name="vbtn-radio" id="vbtn-radio1" autocomplete="off" checked>
            <label class="btn btn-outline-danger" for="vbtn-radio1">画像ファイル</label>
            <input type="radio" class="btn-check" name="vbtn-radio" id="vbtn-radio2" autocomplete="off">
            <label class="btn btn-outline-danger" for="vbtn-radio2">量機能</label>
          </div>
          <div class="col-9">
            <p>*実際の写真を使って量を管理することも、提供されている画像を参考に設定することも可能です。</p>
            <p>*スマートフォン等で写真を撮り直接保存することはできません</p>
          </div>
        </div>

        <div class="mb-3">
          <%= f.label :category_names %><span class="text-danger">*</span>
          <%= f.select :category_names, @category_names.map { |c| [c.category_name, c.category_name] }, { prompt: "選択してください" }, { class: "form-control", required: true } %>
        </div>

        <div class="mb-3">
          <%= f.label :category_types %><span class="text-danger">*</span>
          <%= f.select :category_types, @category_types.map { |c| [c.category_type, c.category_type] }, { prompt: "選択してください" }, { class: "form-control", required: true } %>
        </div>

        <div class="actions">
          <%= f.submit t('helpers.submit.create'), class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>


    <div class="col-md-6" id='previews-form'>
      <div class="image-container text-center">
        <div id="previews" class="border p-3">
          <%= t('helpers.preview') %>
        </div>
      </div>
    </div>

    <div class="col-md-6" id='quantity-previews-form'>
      <div class="quantity-container text-center">
        <div id="quantity-previews" class="border p-3">
          <%= t('helpers.preview') %>
        </div>
      </div>
    </div>
  </div>
</div>
<style>
  .new {
    @media (max-width: 992px) {
      width: 90%;
    }
  }

  .btn-outline-danger {
    font-size: 15px;

    @media (max-width: 992px) {
      font-size: 8px;
      padding-left: 5px;
      padding-right: 5px;
    }
  }

  .actions {
    @media (max-width: 992px) {
      display: flex;
      justify-content: center;
    }
  }
</style>